# Generated by Django 6.0 on 2026-01-05 05:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Futsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('no_of_grounds', models.IntegerField(default=1)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
