# Generated by Django 6.0 on 2026-01-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
