# Generated by Django 6.0.1 on 2026-03-08 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0002_futsal_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='changing_room',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='futsal',
            name='futsal_side',
            field=models.TextField(blank=True, choices=[('5-A Side', '5-A Side'), ('7-A Side', '7-A Side'), ('Both 5-A and 7-A Sides', 'Both 5-A and 7-A Sides')], default='5-A Side', null=True),
        ),
        migrations.AddField(
            model_name='futsal',
            name='parking_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='futsal',
            name='shower_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='futsal',
            name='turf_type',
            field=models.TextField(blank=True, choices=[('Artificial Grass', 'Artificial Grass'), ('Mat', 'Mat'), ('Real Grass', 'Real Grass')], default='Artificial Grass', null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_day', models.CharField(blank=True, null=True)),
                ('booking_slot', models.CharField(blank=True, null=True)),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='futsal', to='futsal.futsal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
