# Generated by Django 6.0.1 on 2026-03-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0003_futsal_changing_room_futsal_futsal_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futsal',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
