# Generated by Django 6.0.1 on 2026-03-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0004_futsal_closing_time_futsal_opening_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_day',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='regular_booking',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.TextField(blank=True, choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed')], default='Pending', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_slot',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
